### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by AlexDigital** [MinecraftCloudSystem/MCS-Core#10]

**Comment by Ghostium** [comment]
Ich würde von MongoDB abraten bzw. zwei komplett verschiedene Datenbank Typen zu benutzen, da einerseits das Management von zwei Datenbank Schemas sehr arbeitsaufwändig ist, zudem die meisten Server-Netzwerke nur MySQL benutzten.

**Comment by lenovouser** [comment]
Ich stimme @Ghostium zu.

**Comment by ilouHD** [comment]
Wir nutzen MongoDB, da die Installation dessen kein großer Aufwand ist und auf einem v/RootServer einfach zu bewerkstelligen ist

//CLOSED
