### ISSUE TITLE
MCS unter Linux nicht möglich zurzeit

### ISSUE THREAD

**Issue by DETommyHD** [MinecraftCloudSystem/MCS-Core#13]
Guten Tag an alle,

und zwar habe ich das MCS auf meinen Server aus Test Gründen schon mal installiert und es startete nicht.
Es sah dann so aus:
node app.js

module.js:340
    throw err;
          ^
Error: Cannot find module './classes/mongo.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/smylegames/MCS/app.js:8:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:497:10)

//NACH EDITING IN DER APP.JS
node app.js

module.js:340
    throw err;
    ^
Error: Cannot find module '../mongo.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/smylegames/MCS/classes/database/daemon.js:9:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/smylegames/MCS/app.js:13:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Ich hatte mal schon alle Schreibfehler behoben, doch Problem ist, bei der Hook.init(); kommt das dies die Standard Hook ist etc. und dann kam noch das in der inject.js ein Fehler wäre:     for(var dir of files) { .
Unter Windows geht alles.
Woran kann das liegen?
MfG
Tom S.

**Comment by ilouHD** [comment]
Hey,

das lag an einer falschen Dateibenennung. Die Datei wurde im Code klein geschrieben, die Änderung von groß ("Mongo.js") zu klein ("mongo.js") hat GitHub allerdings nicht erkannt. Daher kam es zu diesem Fehler. Da nie pulle funktionierte es bei mir. Danke für den Hinweis. Das System sollte nun starten. Falls nicht, bitte melden.

Mit freundlichen Grüßen
ilouHD
MCS Developer

**Comment by DETommyHD** [comment]
Hallo,

leider startet es immer noch nicht unter Linux und Windows. Für einen Bug für beide Versionen habe ich gerade einen Pullrequest herausgebracht. Für die anderen Bugs habe ich dies mal in einem Video verpackt. Link: https://youtu.be/cXfqR6S-Wyo
MfG
Tom S.

**Comment by ilouHD** [comment]
Hey!

Zu deinem Connection-Error:Das liegt daran, dass du eine veraltete config.json(.example) hast. Die aktuelle hat andere Keys. 

Zu deinem 2. Problem (Linux) kann ich dir gerade nichts sagen, außer, dass der Fehler auf meinem Pi nicht entsteht. Nutzt du evtl. eine veraltete NodeJS-Version?
Das kannst du mit dem Befehl "node -v" herausfinden. Sollte es den Befehl "node" nicht geben, lautet dieser "nodejs -v"

Da ich diese Klasse allerdings nicht geschrieben habe und daher eigentlich nicht weiß, wofür CreepPlays sie nutzt / nutzen will, kann ich da eher weniger helfen.

Mit freundlichen Grüßen
ilouHD
MCS Developer

**Comment by DETommyHD** [comment]
Hallo,
danke für deine Antwort. Leider hat mein Debian Server noch Node v0.9.9?!
Werde mal dann den Nodeserver updaten.
PS: Wäre es möglich vllt. noch MongoCredentials einzubauen, für die die dies haben?
//EDIT Aus irgendeinen Grund kann ich Node unter Debian 7 nicht mehr updaten mit apt-get update und apt-get upgrade. Woran liegt das?

MfG
Tom S.

**Comment by ilouHD** [comment]
Hey,

das Problem habe ich bei meinem Pi auch. Dazu kannst du wie folgt vorgehen:
1. Die gewünschte Version herunterladen (Version: 4.2.4 (Stable): "wget https://nodejs.org/dist/v4.2.4/node-v4.2.4-linux-x64.tar.gz")

2. Entpacken: tar -xvf node-v4.2.4-linux-x64.tar.gz
3. Ordner betreten: cd node-v4.2.4-linux-x64.tar.gz
4. Alle Dateien verschieben: sudo cp -R * /usr/local/

Damit kann man einfach per Hand NodeJS installieren. Evtl. füge ich mal ein Script hinzu, das das automatisch macht.

Hoffe es hilft ^^

Mit freundlichen Grüßen
ilouHD
MCS Developer

**Comment by RicoswLive** [comment]
Also bei mir hat es Funktioniert musste paar Fehler beheben das war aber nicht das Problem irgendwie glaube ich das das Projekt hier noch lange dauern wird.
Nach ca. 5 Monaten dürfte man doch schon wenigstens ein Grundgerüst haben.

**Comment by ilouHD** [comment]
Hey,

bitte Teile uns (eher mir) die Fehler mit, damit ich diese Beheben kann.
Das Grundgerüst haben wir doch außerdem schon?!

Mit freundlichen Grüßen
~ ilou

**Comment by RicoswLive** [comment]
Also im Daemon ist der Config Path falsch.

**Comment by ilouHD** [comment]
Wenn du Fehler im Daemon oder im Plugin findest, dann schreibe diese bitte nicht als Issue im Core. Ich habe mit den Funktionen von Daemon und Plugin keine Erfahrung und kann daher nicht groß helfen.
