### ISSUE TITLE
Designs Fehler?

### ISSUE THREAD

**Issue by NojoLP** [MinecraftCloudSystem/MCS-Core#15]
Ist es normal, dass die Strings für die Beschreibungen nicht geladen werden? Ist bei allen Reitern so...
![bildschirmfoto 2016-01-15 um 18 23 23 2](https://cloud.githubusercontent.com/assets/14354391/12359968/656003f2-bbb5-11e5-9f2b-f6bb3843f378.png)

**Comment by DETommyHD** [comment]
Hatte ich auch, aber mit dem neuen Update des MCS sollte es wieder gehen ;)

**Comment by NojoLP** [comment]
Nein geht nicht :/

**Comment by ilouHD** [comment]
Hey!

Das Problem habe ich nicht. Bitte teile uns eventuelle Fehler aus der Konsole mit. Diese kannst du in verschiedenen Browsern anders öffnen. Da ich nur Chrome nutze, kann ich dir nur sagen, wie es dort geht.

Dazu drückst du auf der Webseite die Tastenkombination "Strg" + "Shift" + "C".

Die Konsole sollte sich öffnen und (wahrscheinlich) Fehler ausgeben, da irgendwas bei der Übersetzung nicht funktioniert hat. Dieser Fehler wird uns dann genauere Infos geben, was da falsch ist.

Mit freundlichen Grüßen
ilouHD
MCS Developer

**Comment by NojoLP** [comment]
Mehr konnte ich aus Safari nicht rausbekommen :/ Habt auch auf Chrome probiert, wo es geklappt hat. Alles Übersetzt usw. Aber Safari hat da irgend nen Fehler... Wäre nice, wenn man das bis zu einem Release noch gefixxt bekäme!
![bildschirmfoto 2016-01-16 um 01 44 30 2](https://cloud.githubusercontent.com/assets/14354391/12369106/f8b994be-bbf2-11e5-8407-9f3979551746.png)

**Comment by DETommyHD** [comment]
So wie es aussieht kann er die Dateien nicht abrufen.
Versuche mal im Safari die Dateien so manuell aufzurufen.
MfG
Tom S.
