### ISSUE TITLE
Error auf Debian beim starten

### ISSUE THREAD

**Issue by Z0mGr0HD** [MinecraftCloudSystem/MCS-Core#18]
Hey undzwar bekomme ich diesen error beim starten

/var/www/html/mcs/MCS-Core-master/classes/injector/inject.js:11
    for(var dir of files) {
                ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/mcs/MCS-Core-master/app.js:16:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by DETommyHD** [comment]
Was für eine NodeJS Version hast du denn? Falls du v0.9.9 hast, musst du manuell die v.5.6.0 oder 4.3.1 LTS installieren. Dann sollte es gehen.
MfG
Tom S.

**Comment by Z0mGr0HD** [comment]
ok ein manuelles update hat geholfen benutzt ihr wirklich nur noch mongodb

**Comment by DETommyHD** [comment]
ja

**Comment by ilouHD** [comment]
Hey,

wie bereits gesagt wurde, ja, wir nutzen nur noch MongoDB. Die Verwaltung von 2 Datenbanken an sich wäre gar nicht das Problem. Ist zwar aufwendig, aber nicht so aufwendig wie die Verwaltung von SQL und NoSQL. Da MongoDB NoSQL ist und MySQL SQL haben diese unterschiedliche Funktionsweisen und so weiter.

Anfangs hatte ich sogar beides implementiert, allerdings hab ich dann schon nach wenigen Tagen eine Abstimmung gemacht, welche Datenbank wir nutzen. Da dort MongoDB mit (großem) Abstand gewonnen hat, habe ich MySQL raus genommen.

// Closed

Mit freundlichen Grüßen
~ ilou

**Comment by Z0mGr0HD** [comment]
wie installieren ich mongodb. Ich verzweifle dran????

**Comment by Z0mGr0HD** [comment]
linux debian 8

**Comment by ilouHD** [comment]
Weiß ich nicht :D Nutze es bisher nur auf Windows :D

**Comment by Z0mGr0HD** [comment]
ich kriege fehler über fehler (Beim user erstellen)

**Comment by LucaDev** [comment]
https://docs.mongodb.org/manual/tutorial/install-mongodb-on-linux/

**Comment by Z0mGr0HD** [comment]
hilft mir nicht

**Comment by LucaDev** [comment]
dann brauche ich mehr Informationen zB wie der Fehler überhaupt lautet!

**Comment by Z0mGr0HD** [comment]
haben sie TeamViewer oder Skype
dan könnte man es zusammen machen

**Comment by LucaDev** [comment]
Ich verstehe das Problem nicht, poste doch einfach den Fehler hier herein und ich kann dir sagen, was das Problem ist - oder lass mongo einfach über den root Benutzer laufen (vorerst)

**Comment by Z0mGr0HD** [comment]
naja wir können uns nicht einloggen kein fehler im webinterface ,mongodb kann ich einfach keine datenbank user etc erstellen test function error

**Comment by Z0mGr0HD** [comment]
ok mongodb hat sich erledigt hab mir ne gui genommen aber kann mich nicht einlogen im wi
