### ISSUE TITLE
Ihr macht nicht viel weiter.

### ISSUE THREAD

**Issue by LetsCodingHD-DEV-Malcolm** [MinecraftCloudSystem/MCS-Core#20]
Hey.
Ich bin schon seid Anfang dabei, aber ihr macht immer wenig am CS weiter. Warum?Ich wArte schon so lange. Dauert es noch sehr.lange bis ihr fertig seid?
LG Malcolm

**Comment by ilouHD** [comment]
Dafür sind die Issues nicht gedacht

#closed

**Comment by brainscript** [comment]
@ilouHD Hättest ja trotzdem antworten können. Deine Antwort hört sich eher so an als würdest du nur der Frage ausweichen wollen. Hättest ja auch "Frag mich bitte im Blablabla-Forum" oder so schreiben könne.
