### ISSUE TITLE
CS Auf Win SRV 12

### ISSUE THREAD

**Issue by BrummBrumm03** [MinecraftCloudSystem/MCS-Core#21]
Hallo wie kann man genau auf Windows dass CloudSystem starten denn in einem Video des Systems wird dies auch getan

MfG BrummBrumm

**Comment by DETommyHD** [comment]
Rlly?!
Na gut. CMD Öffnen -> mit "cd" ins Verzeichnis gehen und dort node app.js machen. Falls Pakete noch nicht installiert, "npm install" ausführen.

**Comment by BrummBrumm03** [comment]
Wie soll ich denn npm install ausführen?

**Comment by BrummBrumm03** [comment]
Soo npm install gemacht bekomm immer noch Fehler kannst du denn nicht erklären wie es von anfang an nach npm install weitergeht mit download und installation

**Comment by DETommyHD** [comment]
Kommt etwa der Fehler das npm es nicht gibt oder ein NPM Fehler direkt?

**Comment by DETommyHD** [comment]
Bei sowas bitte auf nodejs.org gehen und dort die Stable version herunter laden und installieren. Außerdem brauchst du MongoDB.

**Comment by BrummBrumm03** [comment]
Was ist das Standard Login?

**Comment by DETommyHD** [comment]
Das bitte mal in die Mongo-Collection einfügen: 
{ "_id" : { "$oid" : "56c738cbd89ff7cc0f1bbd99" }, "username" : "default", "password" : "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f", "lastSID" : "", "backupcode" : 0, "__v" : 0 }



Benutzer: default
Pass: abc

**Comment by ilouHD** [comment]
Du musst dafür das (nicht funktionierende) Setup durchführen. Außerdem funktioniert dieser default-user nicht mehr, da die Hashwerte beim Einloggen anders sind als die beim User.
