### ISSUE TITLE
Design Fehler bei 27" Bildschirm

### ISSUE THREAD

**Issue by lusu007** [MinecraftCloudSystem/MCS-Core#22]
Auf meinem 27" Bildschirm bekomme ich ein blauen Rand unten und rechts am Interface.

http://imgur.com/CNgjD1t

Denke das liegt an den CSS Klassen.

**Comment by ilouHD** [comment]
Hey,

das ist kein Fehler. Wir haben (testweise) beim großen Display die Scrollbar verändert. Da ich gerade an einer Überarbeitung des ganzen CSS-Styles arbeite, wird dies demnächst bei jedem Display so sein.

Mit freundlichen Grüßen
~ ilou

**Comment by lusu007** [comment]
Schon wieder das Design überarbeiten?

**Comment by ilouHD** [comment]
Ich wechsle nur von css zu dem Preprocessor less, da dieser vieles vereinfacht. An für sich bleibt das Design so

**Comment by ilouHD** [comment]
Hey,

Ich wechsle nur von css zu dem Preprocessor less, da dieser vieles vereinfacht und es übersichtlicher ist. An für sich bleibt das Design so.

Mit freundlichen Grüßen
~ ilou
