### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by LetsCodingHD-DEV-Malcolm** [MinecraftCloudSystem/MCS-Core#24]
Immer wenn ich die MongoDB Daten änder werden die auf die Standard Daten zurück gesetzt. (Nach dem MCS) Restart

**Comment by ilouHD** [comment]
Du kannst die Config nur bearbeiten, wenn das MCS abgeschaltet ist. Ansonsten werden Änderungen überschrieben.

**Comment by LetsCodingHD-DEV-Malcolm** [comment]
Ach so okay ich habe es dann falsch gemacht
Am 18.04.2016 22:04 schrieb "ilouHD" <notifications@github.com>:
