### ISSUE TITLE
Ihr macht wartet mur bis niemand mehr interessiert ist am mcs 2.scheiße ..

### ISSUE THREAD

**Issue by LetsCodingHD-DEV-Malcolm** [MinecraftCloudSystem/MCS-Core#27]
Ihr macht das mcs jetzt schon 1-1,5 Jahren und seid verfickt noch mal nicht soweit das man urgendwas machen kann... ich muss 1 monat wRten kann kann ich mir ein 5mal besseres mcs kaufen als auf euren Müll zu wart, was eh nie fertig wird...

**Comment by PostCrafter** [comment]
Wenn es dir nicht passt, kaufe dir doch das andere, bessere MCS, anstatt hier nur ein schlechtes Licht auf dich selber zu werfen.

**Comment by ilouHD** [comment]
Das hier ist immer noch ein Freizeitprojekt. Wir arbeiten nicht beruflich daran und ehrlich gesagt, haben wir keine Lust daran zu arbeiten, wenn wir von Personen, wie zum Beispiel dir, so unter Druck gesetzt werden.

Wenn wir daran arbeiten wollen, dann machen wir das, ansonsten eben nicht. Damit musst du dich dann wohl zurecht finden oder dein anderes MCS kaufen

**Comment by DETommyHD** [comment]
Oder du nimmst dir einen Fork und machst es selber für dich. Es ich ja immer noch nicht unsere Pflicht, alles alleine zu machen. Wir sind ja auch auf die Community angewiesen und freuen uns immer, wenn die Community hilft, das MCS zu releasen.
